# Generated by Django 2.0.1 on 2020-03-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIP', '0002_auto_20200303_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans_option',
            field=models.CharField(max_length=20),
        ),
    ]
