# Generated by Django 2.0.1 on 2020-03-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIP', '0003_auto_20200304_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
