# Generated by Django 3.0.4 on 2020-03-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIP', '0005_auto_20200305_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_comment', models.CharField(max_length=100)),
                ('c_new_quest', models.CharField(max_length=100)),
                ('c_tot_score', models.IntegerField(default=0)),
                ('c_cat_score1', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
