# Generated by Django 3.0.3 on 2020-03-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIP', '0008_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='c_comment',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='c_new_quest',
            field=models.TextField(default='', null=True),
        ),
    ]
