# Generated by Django 3.0.3 on 2020-03-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIP', '0009_auto_20200308_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_text',
            field=models.TextField(default='', null=True),
        ),
    ]
