# Generated by Django 3.0.3 on 2020-03-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIP', '0010_auto_20200310_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
