# Generated by Django 3.0.3 on 2020-03-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIP', '0012_auto_20200311_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='c_tot_score',
            field=models.IntegerField(default=0),
        ),
    ]
