# Generated by Django 3.0.3 on 2020-03-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIP', '0019_questionpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='text',
            field=models.TextField(default='', null=True),
        ),
    ]
