# Generated by Django 3.0.3 on 2020-03-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIP', '0020_auto_20200317_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_questions',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='QuestionPaper',
        ),
    ]
