# Generated by Django 3.0.3 on 2020-03-17 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIP', '0022_question_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
    ]
