# Generated by Django 3.0.3 on 2020-03-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIP', '0023_remove_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_noofquest',
            field=models.IntegerField(default=0),
        ),
    ]
