# Generated by Django 3.0.3 on 2020-03-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIP', '0024_quiz_quiz_noofquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_nooftimestaken',
            field=models.IntegerField(default=0),
        ),
    ]
